### PR TITLE
Do not skip tests

### PR DESCRIPTION
**Pull request by Nyholm**
I know this does not work. But I want to create the PR so we do not forget it.

### CODE REVIEW

**Comment by kelunik** [comment]
@Nyholm You need to rebase / resolve the conflict in addition to rerunning the tests.

**Comment by Nyholm** [comment]
Ill rebase now

**Comment by kelunik** [comment]
I guess we have to fix the required version of the tests, otherwise `--prefer-lowest` will fail.

**Comment by kelunik** [comment]
See https://github.com/php-http/client-integration-tests/pull/33.

**Comment by Nyholm** [comment]
Thank you for merging

**Pull request merged**
